name: gh-pages
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: erlef/setup-beam@v1
        with:
          otp-version: 27
          elixir-version: 1.17

      - run: mix deps.get
      - run: mix credo
      - run: mix dialyzer
      - run: mix test
